version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testDB
    ports:
      - "5436:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
