version: '3.7'

services:

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: 1.zookeeper.nvpsv
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 1
      ZOOKEEPER_SERVERS: 1.zookeeper.nvpsv:2888:3888


  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: 1.kafka.nvpsv
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_COMPRESS_TYPE: 'gzip'
#      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://1.kafka.nvpsv:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      SESSION_TIMEOUT_MS: 1000
      MAX_POLL_RECORDS: 500
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      MAX_POLL_INTERVAL_MS: 30000
      REQUEST_TIMEOUT_MS: 60000
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 600
      KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: 20
      KAFKA_LOG_FLUSH_OFFSET_CHECKPOINT_INTERVAL_MS: 120000
      KAFKA_LOG_FLUSH_START_OFFSET_CHECKPOINT_INTERVAL_MS: 120000
      KAFKA_OFFSET_METADATA_MAX_BYTES: 8192
      KAFKA_REPLICA_FETCH_MAX_BYTES: 157286400
      KAFKA_MESSAGE_MAX_BYTES: 104857600
      KAFKA_MAX_MESSAGE_BYTES: 104857600
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 157286400
      KAFKA_BUFFER_MEMORY: 157286400
