version: '3.1'

networks:
  cassandra:  # docker network where all cassandra nodes will be put in

services:

  cass4:
    image: cassandra:3.11.8   # better to use a specific version, if you want to control upgrades
    container_name: cass4
    hostname: cass4
    networks:
      - cassandra
    ports:
      - "9045:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./data/cass5:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
      - ./etc/cass4:/etc/cassandra   # Use your own config files for full control
    environment: &environment2    # Declare and save environments variables into "environment"
      CASSANDRA_SEEDS: "cass4,cass5"    # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Earth
      CASSANDRA_RACK: West
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128

  cass5:
    image: cassandra:3.11.8
    container_name: cass5
    hostname: cass5
    networks:
      - cassandra
    ports:
      - "9046:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./data/cass5:/var/lib/cassandra    # This is the volume that will persist data for cass2 node
      - ./etc/cass5:/etc/cassandra    # Use your own config files for full control
    environment: *environment2    # point to "environment" to use the same environment variables as cass1
    depends_on:
      - cass4

  cass6:
    image: cassandra:3.11.8
    container_name: cass6
    hostname: cass6
    networks:
      - cassandra
    ports:
      - "9047:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./data/cass6:/var/lib/cassandra    # This is the volume that will persist data for cass3 node
      - ./etc/cass6:/etc/cassandra    # Use your own config files for full control
    environment: *environment2    # point to "environment" to use the same environment variables as cass1
    depends_on:
      - cass4
